# Generated by Django 5.1.6 on 2025-02-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="shares",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
