# Generated by Django 5.1.3 on 2025-02-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cash",
            field=models.DecimalField(decimal_places=2, default=9000.0, max_digits=10),
        ),
    ]
