# Generated by Django 5.1.6 on 2025-02-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_alter_portfolio_shares"),
        ("trading", "0002_customuser_balance_customuser_cash"),
    ]

    operations = []
