# Generated by Django 5.1.6 on 2025-02-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_portfolio_delete_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
            ],
        ),
    ]
