# Generated by Django 5.1.6 on 2025-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_merge_20250216_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="balance",
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cash",
            field=models.FloatField(default=10000.0),
        ),
    ]
