# Generated by Django 5.1.6 on 2025-02-16 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_customuser"),
        ("trading", "0004_alter_customuser_balance_alter_customuser_cash"),
    ]

    operations = []
